### PR TITLE
Refactored Generator a little bit

### PR DESCRIPTION
**Pull request by pamil**
Also updated `.gitignore` to include `composer.lock` and exclude `phpspec.yml` (cause there is `phpspec.yml.dist` bundled with package).

### CODE REVIEW

**Comment by digitalkaoz** [comment]
mh i think its obsolete or? both versions (the current one) and yours do the same (and code qualitity doesnt get better or worse). so i close this one ok? sorry, i thought i quickly do the refactoring myself :/

**Comment by digitalkaoz** [comment]
ah anyway ill merge it, your version is equal, and you added the ignores

**Comment by pamil** [comment]
I get rid of that nested `if` and named some variables and methods to be more natural, also strings are returned on the first return, not the last one. It's no big deal, but IMHO my version is a little bit cleaner.

Anyway, is there any way to download the latest version of phar package?

**Comment by digitalkaoz** [comment]
thats why i merged it ;) it dont know any. would be good if github had an endpoint like `foo/bar/releases/latest/artifact.file`

**Comment by digitalkaoz** [comment]
i have something on the way for that...but not right now...

**Pull request merged**
